#!/bin/bash
cd ..
python encode_sfu_RA_e2e.py 12
python encode_sfu_RA_e2e.py 26
python encode_sfu_RA_e2e.py 40
python encode_sfu_RA_e2e.py 54
python encode_sfu_RA_e2e.py 68
python encode_sfu_RA_e2e.py 82
python encode_sfu_LD_e2e.py 12
python encode_sfu_LD_e2e.py 26
python encode_sfu_LD_e2e.py 40
python encode_sfu_LD_e2e.py 54
python encode_sfu_LD_e2e.py 68
python encode_sfu_LD_e2e.py 82
python encode_sfu_AI_e2e.py 12
python encode_sfu_AI_e2e.py 26
python encode_sfu_AI_e2e.py 40
python encode_sfu_AI_e2e.py 54
python encode_sfu_AI_e2e.py 68
python encode_sfu_AI_e2e.py 82
python encode_sfu_RA_inner.py 12
python encode_sfu_RA_inner.py 26
python encode_sfu_RA_inner.py 40
python encode_sfu_RA_inner.py 54
python encode_sfu_RA_inner.py 68
python encode_sfu_RA_inner.py 82
python encode_sfu_LD_inner.py 12
python encode_sfu_LD_inner.py 26
python encode_sfu_LD_inner.py 40
python encode_sfu_LD_inner.py 54
python encode_sfu_LD_inner.py 68
python encode_sfu_LD_inner.py 82
python encode_sfu_AI_inner.py 12
python encode_sfu_AI_inner.py 26
python encode_sfu_AI_inner.py 40
python encode_sfu_AI_inner.py 54
python encode_sfu_AI_inner.py 68
python encode_sfu_AI_inner.py 82
python encode_tvd_tracking_RA_e2e.py 12
python encode_tvd_tracking_RA_e2e.py 26
python encode_tvd_tracking_RA_e2e.py 40
python encode_tvd_tracking_RA_e2e.py 54
python encode_tvd_tracking_RA_e2e.py 68
python encode_tvd_tracking_RA_e2e.py 82
python encode_tvd_tracking_LD_e2e.py 12
python encode_tvd_tracking_LD_e2e.py 26
python encode_tvd_tracking_LD_e2e.py 40
python encode_tvd_tracking_LD_e2e.py 54
python encode_tvd_tracking_LD_e2e.py 68
python encode_tvd_tracking_LD_e2e.py 82
python encode_tvd_tracking_AI_e2e.py 12
python encode_tvd_tracking_AI_e2e.py 26
python encode_tvd_tracking_AI_e2e.py 40
python encode_tvd_tracking_AI_e2e.py 54
python encode_tvd_tracking_AI_e2e.py 68
python encode_tvd_tracking_AI_e2e.py 82
python encode_tvd_tracking_RA_inner.py 12
python encode_tvd_tracking_RA_inner.py 26
python encode_tvd_tracking_RA_inner.py 40
python encode_tvd_tracking_RA_inner.py 54
python encode_tvd_tracking_RA_inner.py 68
python encode_tvd_tracking_RA_inner.py 82
python encode_tvd_tracking_LD_inner.py 12
python encode_tvd_tracking_LD_inner.py 26
python encode_tvd_tracking_LD_inner.py 40
python encode_tvd_tracking_LD_inner.py 54
python encode_tvd_tracking_LD_inner.py 68
python encode_tvd_tracking_LD_inner.py 82
python encode_tvd_tracking_AI_inner.py 12
python encode_tvd_tracking_AI_inner.py 26
python encode_tvd_tracking_AI_inner.py 40
python encode_tvd_tracking_AI_inner.py 54
python encode_tvd_tracking_AI_inner.py 68
python encode_tvd_tracking_AI_inner.py 82
