#!/bin/bash
cd ..
python encode_sfu_RA_e2e.py 1
python encode_sfu_RA_e2e.py 15
python encode_sfu_RA_e2e.py 29
python encode_sfu_RA_e2e.py 43
python encode_sfu_RA_e2e.py 57
python encode_sfu_RA_e2e.py 71
python encode_sfu_LD_e2e.py 1
python encode_sfu_LD_e2e.py 15
python encode_sfu_LD_e2e.py 29
python encode_sfu_LD_e2e.py 43
python encode_sfu_LD_e2e.py 57
python encode_sfu_LD_e2e.py 71
python encode_sfu_AI_e2e.py 1
python encode_sfu_AI_e2e.py 15
python encode_sfu_AI_e2e.py 29
python encode_sfu_AI_e2e.py 43
python encode_sfu_AI_e2e.py 57
python encode_sfu_AI_e2e.py 71
python encode_sfu_RA_inner.py 1
python encode_sfu_RA_inner.py 15
python encode_sfu_RA_inner.py 29
python encode_sfu_RA_inner.py 43
python encode_sfu_RA_inner.py 57
python encode_sfu_RA_inner.py 71
python encode_sfu_LD_inner.py 1
python encode_sfu_LD_inner.py 15
python encode_sfu_LD_inner.py 29
python encode_sfu_LD_inner.py 43
python encode_sfu_LD_inner.py 57
python encode_sfu_LD_inner.py 71
python encode_sfu_AI_inner.py 1
python encode_sfu_AI_inner.py 15
python encode_sfu_AI_inner.py 29
python encode_sfu_AI_inner.py 43
python encode_sfu_AI_inner.py 57
python encode_sfu_AI_inner.py 71
python encode_tvd_tracking_RA_e2e.py 1
python encode_tvd_tracking_RA_e2e.py 15
python encode_tvd_tracking_RA_e2e.py 29
python encode_tvd_tracking_RA_e2e.py 43
python encode_tvd_tracking_RA_e2e.py 57
python encode_tvd_tracking_RA_e2e.py 71
python encode_tvd_tracking_LD_e2e.py 1
python encode_tvd_tracking_LD_e2e.py 15
python encode_tvd_tracking_LD_e2e.py 29
python encode_tvd_tracking_LD_e2e.py 43
python encode_tvd_tracking_LD_e2e.py 57
python encode_tvd_tracking_LD_e2e.py 71
python encode_tvd_tracking_AI_e2e.py 1
python encode_tvd_tracking_AI_e2e.py 15
python encode_tvd_tracking_AI_e2e.py 29
python encode_tvd_tracking_AI_e2e.py 43
python encode_tvd_tracking_AI_e2e.py 57
python encode_tvd_tracking_AI_e2e.py 71
python encode_tvd_tracking_RA_inner.py 1
python encode_tvd_tracking_RA_inner.py 15
python encode_tvd_tracking_RA_inner.py 29
python encode_tvd_tracking_RA_inner.py 43
python encode_tvd_tracking_RA_inner.py 57
python encode_tvd_tracking_RA_inner.py 71
python encode_tvd_tracking_LD_inner.py 1
python encode_tvd_tracking_LD_inner.py 15
python encode_tvd_tracking_LD_inner.py 29
python encode_tvd_tracking_LD_inner.py 43
python encode_tvd_tracking_LD_inner.py 57
python encode_tvd_tracking_LD_inner.py 71
python encode_tvd_tracking_AI_inner.py 1
python encode_tvd_tracking_AI_inner.py 15
python encode_tvd_tracking_AI_inner.py 29
python encode_tvd_tracking_AI_inner.py 43
python encode_tvd_tracking_AI_inner.py 57
python encode_tvd_tracking_AI_inner.py 71
