#!/bin/bash
cd ..
python encode_sfu_RA_e2e.py 10
python encode_sfu_RA_e2e.py 24
python encode_sfu_RA_e2e.py 38
python encode_sfu_RA_e2e.py 52
python encode_sfu_RA_e2e.py 66
python encode_sfu_RA_e2e.py 80
python encode_sfu_LD_e2e.py 10
python encode_sfu_LD_e2e.py 24
python encode_sfu_LD_e2e.py 38
python encode_sfu_LD_e2e.py 52
python encode_sfu_LD_e2e.py 66
python encode_sfu_LD_e2e.py 80
python encode_sfu_AI_e2e.py 10
python encode_sfu_AI_e2e.py 24
python encode_sfu_AI_e2e.py 38
python encode_sfu_AI_e2e.py 52
python encode_sfu_AI_e2e.py 66
python encode_sfu_AI_e2e.py 80
python encode_sfu_RA_inner.py 10
python encode_sfu_RA_inner.py 24
python encode_sfu_RA_inner.py 38
python encode_sfu_RA_inner.py 52
python encode_sfu_RA_inner.py 66
python encode_sfu_RA_inner.py 80
python encode_sfu_LD_inner.py 10
python encode_sfu_LD_inner.py 24
python encode_sfu_LD_inner.py 38
python encode_sfu_LD_inner.py 52
python encode_sfu_LD_inner.py 66
python encode_sfu_LD_inner.py 80
python encode_sfu_AI_inner.py 10
python encode_sfu_AI_inner.py 24
python encode_sfu_AI_inner.py 38
python encode_sfu_AI_inner.py 52
python encode_sfu_AI_inner.py 66
python encode_sfu_AI_inner.py 80
python encode_tvd_tracking_RA_e2e.py 10
python encode_tvd_tracking_RA_e2e.py 24
python encode_tvd_tracking_RA_e2e.py 38
python encode_tvd_tracking_RA_e2e.py 52
python encode_tvd_tracking_RA_e2e.py 66
python encode_tvd_tracking_RA_e2e.py 80
python encode_tvd_tracking_LD_e2e.py 10
python encode_tvd_tracking_LD_e2e.py 24
python encode_tvd_tracking_LD_e2e.py 38
python encode_tvd_tracking_LD_e2e.py 52
python encode_tvd_tracking_LD_e2e.py 66
python encode_tvd_tracking_LD_e2e.py 80
python encode_tvd_tracking_AI_e2e.py 10
python encode_tvd_tracking_AI_e2e.py 24
python encode_tvd_tracking_AI_e2e.py 38
python encode_tvd_tracking_AI_e2e.py 52
python encode_tvd_tracking_AI_e2e.py 66
python encode_tvd_tracking_AI_e2e.py 80
python encode_tvd_tracking_RA_inner.py 10
python encode_tvd_tracking_RA_inner.py 24
python encode_tvd_tracking_RA_inner.py 38
python encode_tvd_tracking_RA_inner.py 52
python encode_tvd_tracking_RA_inner.py 66
python encode_tvd_tracking_RA_inner.py 80
python encode_tvd_tracking_LD_inner.py 10
python encode_tvd_tracking_LD_inner.py 24
python encode_tvd_tracking_LD_inner.py 38
python encode_tvd_tracking_LD_inner.py 52
python encode_tvd_tracking_LD_inner.py 66
python encode_tvd_tracking_LD_inner.py 80
python encode_tvd_tracking_AI_inner.py 10
python encode_tvd_tracking_AI_inner.py 24
python encode_tvd_tracking_AI_inner.py 38
python encode_tvd_tracking_AI_inner.py 52
python encode_tvd_tracking_AI_inner.py 66
python encode_tvd_tracking_AI_inner.py 80
