#!/bin/bash
cd ..
python encode_sfu_RA_e2e.py 14
python encode_sfu_RA_e2e.py 28
python encode_sfu_RA_e2e.py 42
python encode_sfu_RA_e2e.py 56
python encode_sfu_RA_e2e.py 70
python encode_sfu_RA_e2e.py 84
python encode_sfu_LD_e2e.py 14
python encode_sfu_LD_e2e.py 28
python encode_sfu_LD_e2e.py 42
python encode_sfu_LD_e2e.py 56
python encode_sfu_LD_e2e.py 70
python encode_sfu_LD_e2e.py 84
python encode_sfu_AI_e2e.py 14
python encode_sfu_AI_e2e.py 28
python encode_sfu_AI_e2e.py 42
python encode_sfu_AI_e2e.py 56
python encode_sfu_AI_e2e.py 70
python encode_sfu_AI_e2e.py 84
python encode_sfu_RA_inner.py 14
python encode_sfu_RA_inner.py 28
python encode_sfu_RA_inner.py 42
python encode_sfu_RA_inner.py 56
python encode_sfu_RA_inner.py 70
python encode_sfu_RA_inner.py 84
python encode_sfu_LD_inner.py 14
python encode_sfu_LD_inner.py 28
python encode_sfu_LD_inner.py 42
python encode_sfu_LD_inner.py 56
python encode_sfu_LD_inner.py 70
python encode_sfu_LD_inner.py 84
python encode_sfu_AI_inner.py 14
python encode_sfu_AI_inner.py 28
python encode_sfu_AI_inner.py 42
python encode_sfu_AI_inner.py 56
python encode_sfu_AI_inner.py 70
python encode_sfu_AI_inner.py 84
python encode_tvd_tracking_RA_e2e.py 14
python encode_tvd_tracking_RA_e2e.py 28
python encode_tvd_tracking_RA_e2e.py 42
python encode_tvd_tracking_RA_e2e.py 56
python encode_tvd_tracking_RA_e2e.py 70
python encode_tvd_tracking_RA_e2e.py 84
python encode_tvd_tracking_LD_e2e.py 14
python encode_tvd_tracking_LD_e2e.py 28
python encode_tvd_tracking_LD_e2e.py 42
python encode_tvd_tracking_LD_e2e.py 56
python encode_tvd_tracking_LD_e2e.py 70
python encode_tvd_tracking_LD_e2e.py 84
python encode_tvd_tracking_AI_e2e.py 14
python encode_tvd_tracking_AI_e2e.py 28
python encode_tvd_tracking_AI_e2e.py 42
python encode_tvd_tracking_AI_e2e.py 56
python encode_tvd_tracking_AI_e2e.py 70
python encode_tvd_tracking_AI_e2e.py 84
python encode_tvd_tracking_RA_inner.py 14
python encode_tvd_tracking_RA_inner.py 28
python encode_tvd_tracking_RA_inner.py 42
python encode_tvd_tracking_RA_inner.py 56
python encode_tvd_tracking_RA_inner.py 70
python encode_tvd_tracking_RA_inner.py 84
python encode_tvd_tracking_LD_inner.py 14
python encode_tvd_tracking_LD_inner.py 28
python encode_tvd_tracking_LD_inner.py 42
python encode_tvd_tracking_LD_inner.py 56
python encode_tvd_tracking_LD_inner.py 70
python encode_tvd_tracking_LD_inner.py 84
python encode_tvd_tracking_AI_inner.py 14
python encode_tvd_tracking_AI_inner.py 28
python encode_tvd_tracking_AI_inner.py 42
python encode_tvd_tracking_AI_inner.py 56
python encode_tvd_tracking_AI_inner.py 70
python encode_tvd_tracking_AI_inner.py 84
