#!/bin/bash
cd ..
python encode_sfu_RA_e2e.py 13
python encode_sfu_RA_e2e.py 27
python encode_sfu_RA_e2e.py 41
python encode_sfu_RA_e2e.py 55
python encode_sfu_RA_e2e.py 69
python encode_sfu_RA_e2e.py 83
python encode_sfu_LD_e2e.py 13
python encode_sfu_LD_e2e.py 27
python encode_sfu_LD_e2e.py 41
python encode_sfu_LD_e2e.py 55
python encode_sfu_LD_e2e.py 69
python encode_sfu_LD_e2e.py 83
python encode_sfu_AI_e2e.py 13
python encode_sfu_AI_e2e.py 27
python encode_sfu_AI_e2e.py 41
python encode_sfu_AI_e2e.py 55
python encode_sfu_AI_e2e.py 69
python encode_sfu_AI_e2e.py 83
python encode_sfu_RA_inner.py 13
python encode_sfu_RA_inner.py 27
python encode_sfu_RA_inner.py 41
python encode_sfu_RA_inner.py 55
python encode_sfu_RA_inner.py 69
python encode_sfu_RA_inner.py 83
python encode_sfu_LD_inner.py 13
python encode_sfu_LD_inner.py 27
python encode_sfu_LD_inner.py 41
python encode_sfu_LD_inner.py 55
python encode_sfu_LD_inner.py 69
python encode_sfu_LD_inner.py 83
python encode_sfu_AI_inner.py 13
python encode_sfu_AI_inner.py 27
python encode_sfu_AI_inner.py 41
python encode_sfu_AI_inner.py 55
python encode_sfu_AI_inner.py 69
python encode_sfu_AI_inner.py 83
python encode_tvd_tracking_RA_e2e.py 13
python encode_tvd_tracking_RA_e2e.py 27
python encode_tvd_tracking_RA_e2e.py 41
python encode_tvd_tracking_RA_e2e.py 55
python encode_tvd_tracking_RA_e2e.py 69
python encode_tvd_tracking_RA_e2e.py 83
python encode_tvd_tracking_LD_e2e.py 13
python encode_tvd_tracking_LD_e2e.py 27
python encode_tvd_tracking_LD_e2e.py 41
python encode_tvd_tracking_LD_e2e.py 55
python encode_tvd_tracking_LD_e2e.py 69
python encode_tvd_tracking_LD_e2e.py 83
python encode_tvd_tracking_AI_e2e.py 13
python encode_tvd_tracking_AI_e2e.py 27
python encode_tvd_tracking_AI_e2e.py 41
python encode_tvd_tracking_AI_e2e.py 55
python encode_tvd_tracking_AI_e2e.py 69
python encode_tvd_tracking_AI_e2e.py 83
python encode_tvd_tracking_RA_inner.py 13
python encode_tvd_tracking_RA_inner.py 27
python encode_tvd_tracking_RA_inner.py 41
python encode_tvd_tracking_RA_inner.py 55
python encode_tvd_tracking_RA_inner.py 69
python encode_tvd_tracking_RA_inner.py 83
python encode_tvd_tracking_LD_inner.py 13
python encode_tvd_tracking_LD_inner.py 27
python encode_tvd_tracking_LD_inner.py 41
python encode_tvd_tracking_LD_inner.py 55
python encode_tvd_tracking_LD_inner.py 69
python encode_tvd_tracking_LD_inner.py 83
python encode_tvd_tracking_AI_inner.py 13
python encode_tvd_tracking_AI_inner.py 27
python encode_tvd_tracking_AI_inner.py 41
python encode_tvd_tracking_AI_inner.py 55
python encode_tvd_tracking_AI_inner.py 69
python encode_tvd_tracking_AI_inner.py 83
