#!/bin/bash
cd ..
python encode_sfu_RA_e2e.py 2
python encode_sfu_RA_e2e.py 16
python encode_sfu_RA_e2e.py 30
python encode_sfu_RA_e2e.py 44
python encode_sfu_RA_e2e.py 58
python encode_sfu_RA_e2e.py 72
python encode_sfu_LD_e2e.py 2
python encode_sfu_LD_e2e.py 16
python encode_sfu_LD_e2e.py 30
python encode_sfu_LD_e2e.py 44
python encode_sfu_LD_e2e.py 58
python encode_sfu_LD_e2e.py 72
python encode_sfu_AI_e2e.py 2
python encode_sfu_AI_e2e.py 16
python encode_sfu_AI_e2e.py 30
python encode_sfu_AI_e2e.py 44
python encode_sfu_AI_e2e.py 58
python encode_sfu_AI_e2e.py 72
python encode_sfu_RA_inner.py 2
python encode_sfu_RA_inner.py 16
python encode_sfu_RA_inner.py 30
python encode_sfu_RA_inner.py 44
python encode_sfu_RA_inner.py 58
python encode_sfu_RA_inner.py 72
python encode_sfu_LD_inner.py 2
python encode_sfu_LD_inner.py 16
python encode_sfu_LD_inner.py 30
python encode_sfu_LD_inner.py 44
python encode_sfu_LD_inner.py 58
python encode_sfu_LD_inner.py 72
python encode_sfu_AI_inner.py 2
python encode_sfu_AI_inner.py 16
python encode_sfu_AI_inner.py 30
python encode_sfu_AI_inner.py 44
python encode_sfu_AI_inner.py 58
python encode_sfu_AI_inner.py 72
python encode_tvd_tracking_RA_e2e.py 2
python encode_tvd_tracking_RA_e2e.py 16
python encode_tvd_tracking_RA_e2e.py 30
python encode_tvd_tracking_RA_e2e.py 44
python encode_tvd_tracking_RA_e2e.py 58
python encode_tvd_tracking_RA_e2e.py 72
python encode_tvd_tracking_LD_e2e.py 2
python encode_tvd_tracking_LD_e2e.py 16
python encode_tvd_tracking_LD_e2e.py 30
python encode_tvd_tracking_LD_e2e.py 44
python encode_tvd_tracking_LD_e2e.py 58
python encode_tvd_tracking_LD_e2e.py 72
python encode_tvd_tracking_AI_e2e.py 2
python encode_tvd_tracking_AI_e2e.py 16
python encode_tvd_tracking_AI_e2e.py 30
python encode_tvd_tracking_AI_e2e.py 44
python encode_tvd_tracking_AI_e2e.py 58
python encode_tvd_tracking_AI_e2e.py 72
python encode_tvd_tracking_RA_inner.py 2
python encode_tvd_tracking_RA_inner.py 16
python encode_tvd_tracking_RA_inner.py 30
python encode_tvd_tracking_RA_inner.py 44
python encode_tvd_tracking_RA_inner.py 58
python encode_tvd_tracking_RA_inner.py 72
python encode_tvd_tracking_LD_inner.py 2
python encode_tvd_tracking_LD_inner.py 16
python encode_tvd_tracking_LD_inner.py 30
python encode_tvd_tracking_LD_inner.py 44
python encode_tvd_tracking_LD_inner.py 58
python encode_tvd_tracking_LD_inner.py 72
python encode_tvd_tracking_AI_inner.py 2
python encode_tvd_tracking_AI_inner.py 16
python encode_tvd_tracking_AI_inner.py 30
python encode_tvd_tracking_AI_inner.py 44
python encode_tvd_tracking_AI_inner.py 58
python encode_tvd_tracking_AI_inner.py 72
