#!/bin/bash
cd ..
python encode_sfu_RA_e2e.py 3
python encode_sfu_RA_e2e.py 17
python encode_sfu_RA_e2e.py 31
python encode_sfu_RA_e2e.py 45
python encode_sfu_RA_e2e.py 59
python encode_sfu_RA_e2e.py 73
python encode_sfu_LD_e2e.py 3
python encode_sfu_LD_e2e.py 17
python encode_sfu_LD_e2e.py 31
python encode_sfu_LD_e2e.py 45
python encode_sfu_LD_e2e.py 59
python encode_sfu_LD_e2e.py 73
python encode_sfu_AI_e2e.py 3
python encode_sfu_AI_e2e.py 17
python encode_sfu_AI_e2e.py 31
python encode_sfu_AI_e2e.py 45
python encode_sfu_AI_e2e.py 59
python encode_sfu_AI_e2e.py 73
python encode_sfu_RA_inner.py 3
python encode_sfu_RA_inner.py 17
python encode_sfu_RA_inner.py 31
python encode_sfu_RA_inner.py 45
python encode_sfu_RA_inner.py 59
python encode_sfu_RA_inner.py 73
python encode_sfu_LD_inner.py 3
python encode_sfu_LD_inner.py 17
python encode_sfu_LD_inner.py 31
python encode_sfu_LD_inner.py 45
python encode_sfu_LD_inner.py 59
python encode_sfu_LD_inner.py 73
python encode_sfu_AI_inner.py 3
python encode_sfu_AI_inner.py 17
python encode_sfu_AI_inner.py 31
python encode_sfu_AI_inner.py 45
python encode_sfu_AI_inner.py 59
python encode_sfu_AI_inner.py 73
python encode_tvd_tracking_RA_e2e.py 3
python encode_tvd_tracking_RA_e2e.py 17
python encode_tvd_tracking_RA_e2e.py 31
python encode_tvd_tracking_RA_e2e.py 45
python encode_tvd_tracking_RA_e2e.py 59
python encode_tvd_tracking_RA_e2e.py 73
python encode_tvd_tracking_LD_e2e.py 3
python encode_tvd_tracking_LD_e2e.py 17
python encode_tvd_tracking_LD_e2e.py 31
python encode_tvd_tracking_LD_e2e.py 45
python encode_tvd_tracking_LD_e2e.py 59
python encode_tvd_tracking_LD_e2e.py 73
python encode_tvd_tracking_AI_e2e.py 3
python encode_tvd_tracking_AI_e2e.py 17
python encode_tvd_tracking_AI_e2e.py 31
python encode_tvd_tracking_AI_e2e.py 45
python encode_tvd_tracking_AI_e2e.py 59
python encode_tvd_tracking_AI_e2e.py 73
python encode_tvd_tracking_RA_inner.py 3
python encode_tvd_tracking_RA_inner.py 17
python encode_tvd_tracking_RA_inner.py 31
python encode_tvd_tracking_RA_inner.py 45
python encode_tvd_tracking_RA_inner.py 59
python encode_tvd_tracking_RA_inner.py 73
python encode_tvd_tracking_LD_inner.py 3
python encode_tvd_tracking_LD_inner.py 17
python encode_tvd_tracking_LD_inner.py 31
python encode_tvd_tracking_LD_inner.py 45
python encode_tvd_tracking_LD_inner.py 59
python encode_tvd_tracking_LD_inner.py 73
python encode_tvd_tracking_AI_inner.py 3
python encode_tvd_tracking_AI_inner.py 17
python encode_tvd_tracking_AI_inner.py 31
python encode_tvd_tracking_AI_inner.py 45
python encode_tvd_tracking_AI_inner.py 59
python encode_tvd_tracking_AI_inner.py 73
