#!/bin/bash
cd ..
python encode_sfu_RA_e2e.py 4
python encode_sfu_RA_e2e.py 18
python encode_sfu_RA_e2e.py 32
python encode_sfu_RA_e2e.py 46
python encode_sfu_RA_e2e.py 60
python encode_sfu_RA_e2e.py 74
python encode_sfu_LD_e2e.py 4
python encode_sfu_LD_e2e.py 18
python encode_sfu_LD_e2e.py 32
python encode_sfu_LD_e2e.py 46
python encode_sfu_LD_e2e.py 60
python encode_sfu_LD_e2e.py 74
python encode_sfu_AI_e2e.py 4
python encode_sfu_AI_e2e.py 18
python encode_sfu_AI_e2e.py 32
python encode_sfu_AI_e2e.py 46
python encode_sfu_AI_e2e.py 60
python encode_sfu_AI_e2e.py 74
python encode_sfu_RA_inner.py 4
python encode_sfu_RA_inner.py 18
python encode_sfu_RA_inner.py 32
python encode_sfu_RA_inner.py 46
python encode_sfu_RA_inner.py 60
python encode_sfu_RA_inner.py 74
python encode_sfu_LD_inner.py 4
python encode_sfu_LD_inner.py 18
python encode_sfu_LD_inner.py 32
python encode_sfu_LD_inner.py 46
python encode_sfu_LD_inner.py 60
python encode_sfu_LD_inner.py 74
python encode_sfu_AI_inner.py 4
python encode_sfu_AI_inner.py 18
python encode_sfu_AI_inner.py 32
python encode_sfu_AI_inner.py 46
python encode_sfu_AI_inner.py 60
python encode_sfu_AI_inner.py 74
python encode_tvd_tracking_RA_e2e.py 4
python encode_tvd_tracking_RA_e2e.py 18
python encode_tvd_tracking_RA_e2e.py 32
python encode_tvd_tracking_RA_e2e.py 46
python encode_tvd_tracking_RA_e2e.py 60
python encode_tvd_tracking_RA_e2e.py 74
python encode_tvd_tracking_LD_e2e.py 4
python encode_tvd_tracking_LD_e2e.py 18
python encode_tvd_tracking_LD_e2e.py 32
python encode_tvd_tracking_LD_e2e.py 46
python encode_tvd_tracking_LD_e2e.py 60
python encode_tvd_tracking_LD_e2e.py 74
python encode_tvd_tracking_AI_e2e.py 4
python encode_tvd_tracking_AI_e2e.py 18
python encode_tvd_tracking_AI_e2e.py 32
python encode_tvd_tracking_AI_e2e.py 46
python encode_tvd_tracking_AI_e2e.py 60
python encode_tvd_tracking_AI_e2e.py 74
python encode_tvd_tracking_RA_inner.py 4
python encode_tvd_tracking_RA_inner.py 18
python encode_tvd_tracking_RA_inner.py 32
python encode_tvd_tracking_RA_inner.py 46
python encode_tvd_tracking_RA_inner.py 60
python encode_tvd_tracking_RA_inner.py 74
python encode_tvd_tracking_LD_inner.py 4
python encode_tvd_tracking_LD_inner.py 18
python encode_tvd_tracking_LD_inner.py 32
python encode_tvd_tracking_LD_inner.py 46
python encode_tvd_tracking_LD_inner.py 60
python encode_tvd_tracking_LD_inner.py 74
python encode_tvd_tracking_AI_inner.py 4
python encode_tvd_tracking_AI_inner.py 18
python encode_tvd_tracking_AI_inner.py 32
python encode_tvd_tracking_AI_inner.py 46
python encode_tvd_tracking_AI_inner.py 60
python encode_tvd_tracking_AI_inner.py 74
