#!/bin/bash
cd ..
python encode_sfu_RA_e2e.py 5
python encode_sfu_RA_e2e.py 19
python encode_sfu_RA_e2e.py 33
python encode_sfu_RA_e2e.py 47
python encode_sfu_RA_e2e.py 61
python encode_sfu_RA_e2e.py 75
python encode_sfu_LD_e2e.py 5
python encode_sfu_LD_e2e.py 19
python encode_sfu_LD_e2e.py 33
python encode_sfu_LD_e2e.py 47
python encode_sfu_LD_e2e.py 61
python encode_sfu_LD_e2e.py 75
python encode_sfu_AI_e2e.py 5
python encode_sfu_AI_e2e.py 19
python encode_sfu_AI_e2e.py 33
python encode_sfu_AI_e2e.py 47
python encode_sfu_AI_e2e.py 61
python encode_sfu_AI_e2e.py 75
python encode_sfu_RA_inner.py 5
python encode_sfu_RA_inner.py 19
python encode_sfu_RA_inner.py 33
python encode_sfu_RA_inner.py 47
python encode_sfu_RA_inner.py 61
python encode_sfu_RA_inner.py 75
python encode_sfu_LD_inner.py 5
python encode_sfu_LD_inner.py 19
python encode_sfu_LD_inner.py 33
python encode_sfu_LD_inner.py 47
python encode_sfu_LD_inner.py 61
python encode_sfu_LD_inner.py 75
python encode_sfu_AI_inner.py 5
python encode_sfu_AI_inner.py 19
python encode_sfu_AI_inner.py 33
python encode_sfu_AI_inner.py 47
python encode_sfu_AI_inner.py 61
python encode_sfu_AI_inner.py 75
python encode_tvd_tracking_RA_e2e.py 5
python encode_tvd_tracking_RA_e2e.py 19
python encode_tvd_tracking_RA_e2e.py 33
python encode_tvd_tracking_RA_e2e.py 47
python encode_tvd_tracking_RA_e2e.py 61
python encode_tvd_tracking_RA_e2e.py 75
python encode_tvd_tracking_LD_e2e.py 5
python encode_tvd_tracking_LD_e2e.py 19
python encode_tvd_tracking_LD_e2e.py 33
python encode_tvd_tracking_LD_e2e.py 47
python encode_tvd_tracking_LD_e2e.py 61
python encode_tvd_tracking_LD_e2e.py 75
python encode_tvd_tracking_AI_e2e.py 5
python encode_tvd_tracking_AI_e2e.py 19
python encode_tvd_tracking_AI_e2e.py 33
python encode_tvd_tracking_AI_e2e.py 47
python encode_tvd_tracking_AI_e2e.py 61
python encode_tvd_tracking_AI_e2e.py 75
python encode_tvd_tracking_RA_inner.py 5
python encode_tvd_tracking_RA_inner.py 19
python encode_tvd_tracking_RA_inner.py 33
python encode_tvd_tracking_RA_inner.py 47
python encode_tvd_tracking_RA_inner.py 61
python encode_tvd_tracking_RA_inner.py 75
python encode_tvd_tracking_LD_inner.py 5
python encode_tvd_tracking_LD_inner.py 19
python encode_tvd_tracking_LD_inner.py 33
python encode_tvd_tracking_LD_inner.py 47
python encode_tvd_tracking_LD_inner.py 61
python encode_tvd_tracking_LD_inner.py 75
python encode_tvd_tracking_AI_inner.py 5
python encode_tvd_tracking_AI_inner.py 19
python encode_tvd_tracking_AI_inner.py 33
python encode_tvd_tracking_AI_inner.py 47
python encode_tvd_tracking_AI_inner.py 61
python encode_tvd_tracking_AI_inner.py 75
