#!/bin/bash
cd ..
python encode_sfu_RA_e2e.py 6
python encode_sfu_RA_e2e.py 20
python encode_sfu_RA_e2e.py 34
python encode_sfu_RA_e2e.py 48
python encode_sfu_RA_e2e.py 62
python encode_sfu_RA_e2e.py 76
python encode_sfu_LD_e2e.py 6
python encode_sfu_LD_e2e.py 20
python encode_sfu_LD_e2e.py 34
python encode_sfu_LD_e2e.py 48
python encode_sfu_LD_e2e.py 62
python encode_sfu_LD_e2e.py 76
python encode_sfu_AI_e2e.py 6
python encode_sfu_AI_e2e.py 20
python encode_sfu_AI_e2e.py 34
python encode_sfu_AI_e2e.py 48
python encode_sfu_AI_e2e.py 62
python encode_sfu_AI_e2e.py 76
python encode_sfu_RA_inner.py 6
python encode_sfu_RA_inner.py 20
python encode_sfu_RA_inner.py 34
python encode_sfu_RA_inner.py 48
python encode_sfu_RA_inner.py 62
python encode_sfu_RA_inner.py 76
python encode_sfu_LD_inner.py 6
python encode_sfu_LD_inner.py 20
python encode_sfu_LD_inner.py 34
python encode_sfu_LD_inner.py 48
python encode_sfu_LD_inner.py 62
python encode_sfu_LD_inner.py 76
python encode_sfu_AI_inner.py 6
python encode_sfu_AI_inner.py 20
python encode_sfu_AI_inner.py 34
python encode_sfu_AI_inner.py 48
python encode_sfu_AI_inner.py 62
python encode_sfu_AI_inner.py 76
python encode_tvd_tracking_RA_e2e.py 6
python encode_tvd_tracking_RA_e2e.py 20
python encode_tvd_tracking_RA_e2e.py 34
python encode_tvd_tracking_RA_e2e.py 48
python encode_tvd_tracking_RA_e2e.py 62
python encode_tvd_tracking_RA_e2e.py 76
python encode_tvd_tracking_LD_e2e.py 6
python encode_tvd_tracking_LD_e2e.py 20
python encode_tvd_tracking_LD_e2e.py 34
python encode_tvd_tracking_LD_e2e.py 48
python encode_tvd_tracking_LD_e2e.py 62
python encode_tvd_tracking_LD_e2e.py 76
python encode_tvd_tracking_AI_e2e.py 6
python encode_tvd_tracking_AI_e2e.py 20
python encode_tvd_tracking_AI_e2e.py 34
python encode_tvd_tracking_AI_e2e.py 48
python encode_tvd_tracking_AI_e2e.py 62
python encode_tvd_tracking_AI_e2e.py 76
python encode_tvd_tracking_RA_inner.py 6
python encode_tvd_tracking_RA_inner.py 20
python encode_tvd_tracking_RA_inner.py 34
python encode_tvd_tracking_RA_inner.py 48
python encode_tvd_tracking_RA_inner.py 62
python encode_tvd_tracking_RA_inner.py 76
python encode_tvd_tracking_LD_inner.py 6
python encode_tvd_tracking_LD_inner.py 20
python encode_tvd_tracking_LD_inner.py 34
python encode_tvd_tracking_LD_inner.py 48
python encode_tvd_tracking_LD_inner.py 62
python encode_tvd_tracking_LD_inner.py 76
python encode_tvd_tracking_AI_inner.py 6
python encode_tvd_tracking_AI_inner.py 20
python encode_tvd_tracking_AI_inner.py 34
python encode_tvd_tracking_AI_inner.py 48
python encode_tvd_tracking_AI_inner.py 62
python encode_tvd_tracking_AI_inner.py 76
