#!/bin/bash
cd ..
python encode_sfu_RA_e2e.py 7
python encode_sfu_RA_e2e.py 21
python encode_sfu_RA_e2e.py 35
python encode_sfu_RA_e2e.py 49
python encode_sfu_RA_e2e.py 63
python encode_sfu_RA_e2e.py 77
python encode_sfu_LD_e2e.py 7
python encode_sfu_LD_e2e.py 21
python encode_sfu_LD_e2e.py 35
python encode_sfu_LD_e2e.py 49
python encode_sfu_LD_e2e.py 63
python encode_sfu_LD_e2e.py 77
python encode_sfu_AI_e2e.py 7
python encode_sfu_AI_e2e.py 21
python encode_sfu_AI_e2e.py 35
python encode_sfu_AI_e2e.py 49
python encode_sfu_AI_e2e.py 63
python encode_sfu_AI_e2e.py 77
python encode_sfu_RA_inner.py 7
python encode_sfu_RA_inner.py 21
python encode_sfu_RA_inner.py 35
python encode_sfu_RA_inner.py 49
python encode_sfu_RA_inner.py 63
python encode_sfu_RA_inner.py 77
python encode_sfu_LD_inner.py 7
python encode_sfu_LD_inner.py 21
python encode_sfu_LD_inner.py 35
python encode_sfu_LD_inner.py 49
python encode_sfu_LD_inner.py 63
python encode_sfu_LD_inner.py 77
python encode_sfu_AI_inner.py 7
python encode_sfu_AI_inner.py 21
python encode_sfu_AI_inner.py 35
python encode_sfu_AI_inner.py 49
python encode_sfu_AI_inner.py 63
python encode_sfu_AI_inner.py 77
python encode_tvd_tracking_RA_e2e.py 7
python encode_tvd_tracking_RA_e2e.py 21
python encode_tvd_tracking_RA_e2e.py 35
python encode_tvd_tracking_RA_e2e.py 49
python encode_tvd_tracking_RA_e2e.py 63
python encode_tvd_tracking_RA_e2e.py 77
python encode_tvd_tracking_LD_e2e.py 7
python encode_tvd_tracking_LD_e2e.py 21
python encode_tvd_tracking_LD_e2e.py 35
python encode_tvd_tracking_LD_e2e.py 49
python encode_tvd_tracking_LD_e2e.py 63
python encode_tvd_tracking_LD_e2e.py 77
python encode_tvd_tracking_AI_e2e.py 7
python encode_tvd_tracking_AI_e2e.py 21
python encode_tvd_tracking_AI_e2e.py 35
python encode_tvd_tracking_AI_e2e.py 49
python encode_tvd_tracking_AI_e2e.py 63
python encode_tvd_tracking_AI_e2e.py 77
python encode_tvd_tracking_RA_inner.py 7
python encode_tvd_tracking_RA_inner.py 21
python encode_tvd_tracking_RA_inner.py 35
python encode_tvd_tracking_RA_inner.py 49
python encode_tvd_tracking_RA_inner.py 63
python encode_tvd_tracking_RA_inner.py 77
python encode_tvd_tracking_LD_inner.py 7
python encode_tvd_tracking_LD_inner.py 21
python encode_tvd_tracking_LD_inner.py 35
python encode_tvd_tracking_LD_inner.py 49
python encode_tvd_tracking_LD_inner.py 63
python encode_tvd_tracking_LD_inner.py 77
python encode_tvd_tracking_AI_inner.py 7
python encode_tvd_tracking_AI_inner.py 21
python encode_tvd_tracking_AI_inner.py 35
python encode_tvd_tracking_AI_inner.py 49
python encode_tvd_tracking_AI_inner.py 63
python encode_tvd_tracking_AI_inner.py 77
