#!/bin/bash
cd ..
python encode_sfu_RA_e2e.py 8
python encode_sfu_RA_e2e.py 22
python encode_sfu_RA_e2e.py 36
python encode_sfu_RA_e2e.py 50
python encode_sfu_RA_e2e.py 64
python encode_sfu_RA_e2e.py 78
python encode_sfu_LD_e2e.py 8
python encode_sfu_LD_e2e.py 22
python encode_sfu_LD_e2e.py 36
python encode_sfu_LD_e2e.py 50
python encode_sfu_LD_e2e.py 64
python encode_sfu_LD_e2e.py 78
python encode_sfu_AI_e2e.py 8
python encode_sfu_AI_e2e.py 22
python encode_sfu_AI_e2e.py 36
python encode_sfu_AI_e2e.py 50
python encode_sfu_AI_e2e.py 64
python encode_sfu_AI_e2e.py 78
python encode_sfu_RA_inner.py 8
python encode_sfu_RA_inner.py 22
python encode_sfu_RA_inner.py 36
python encode_sfu_RA_inner.py 50
python encode_sfu_RA_inner.py 64
python encode_sfu_RA_inner.py 78
python encode_sfu_LD_inner.py 8
python encode_sfu_LD_inner.py 22
python encode_sfu_LD_inner.py 36
python encode_sfu_LD_inner.py 50
python encode_sfu_LD_inner.py 64
python encode_sfu_LD_inner.py 78
python encode_sfu_AI_inner.py 8
python encode_sfu_AI_inner.py 22
python encode_sfu_AI_inner.py 36
python encode_sfu_AI_inner.py 50
python encode_sfu_AI_inner.py 64
python encode_sfu_AI_inner.py 78
python encode_tvd_tracking_RA_e2e.py 8
python encode_tvd_tracking_RA_e2e.py 22
python encode_tvd_tracking_RA_e2e.py 36
python encode_tvd_tracking_RA_e2e.py 50
python encode_tvd_tracking_RA_e2e.py 64
python encode_tvd_tracking_RA_e2e.py 78
python encode_tvd_tracking_LD_e2e.py 8
python encode_tvd_tracking_LD_e2e.py 22
python encode_tvd_tracking_LD_e2e.py 36
python encode_tvd_tracking_LD_e2e.py 50
python encode_tvd_tracking_LD_e2e.py 64
python encode_tvd_tracking_LD_e2e.py 78
python encode_tvd_tracking_AI_e2e.py 8
python encode_tvd_tracking_AI_e2e.py 22
python encode_tvd_tracking_AI_e2e.py 36
python encode_tvd_tracking_AI_e2e.py 50
python encode_tvd_tracking_AI_e2e.py 64
python encode_tvd_tracking_AI_e2e.py 78
python encode_tvd_tracking_RA_inner.py 8
python encode_tvd_tracking_RA_inner.py 22
python encode_tvd_tracking_RA_inner.py 36
python encode_tvd_tracking_RA_inner.py 50
python encode_tvd_tracking_RA_inner.py 64
python encode_tvd_tracking_RA_inner.py 78
python encode_tvd_tracking_LD_inner.py 8
python encode_tvd_tracking_LD_inner.py 22
python encode_tvd_tracking_LD_inner.py 36
python encode_tvd_tracking_LD_inner.py 50
python encode_tvd_tracking_LD_inner.py 64
python encode_tvd_tracking_LD_inner.py 78
python encode_tvd_tracking_AI_inner.py 8
python encode_tvd_tracking_AI_inner.py 22
python encode_tvd_tracking_AI_inner.py 36
python encode_tvd_tracking_AI_inner.py 50
python encode_tvd_tracking_AI_inner.py 64
python encode_tvd_tracking_AI_inner.py 78
