#!/bin/bash
cd ..
python encode_sfu_RA_e2e.py 9
python encode_sfu_RA_e2e.py 23
python encode_sfu_RA_e2e.py 37
python encode_sfu_RA_e2e.py 51
python encode_sfu_RA_e2e.py 65
python encode_sfu_RA_e2e.py 79
python encode_sfu_LD_e2e.py 9
python encode_sfu_LD_e2e.py 23
python encode_sfu_LD_e2e.py 37
python encode_sfu_LD_e2e.py 51
python encode_sfu_LD_e2e.py 65
python encode_sfu_LD_e2e.py 79
python encode_sfu_AI_e2e.py 9
python encode_sfu_AI_e2e.py 23
python encode_sfu_AI_e2e.py 37
python encode_sfu_AI_e2e.py 51
python encode_sfu_AI_e2e.py 65
python encode_sfu_AI_e2e.py 79
python encode_sfu_RA_inner.py 9
python encode_sfu_RA_inner.py 23
python encode_sfu_RA_inner.py 37
python encode_sfu_RA_inner.py 51
python encode_sfu_RA_inner.py 65
python encode_sfu_RA_inner.py 79
python encode_sfu_LD_inner.py 9
python encode_sfu_LD_inner.py 23
python encode_sfu_LD_inner.py 37
python encode_sfu_LD_inner.py 51
python encode_sfu_LD_inner.py 65
python encode_sfu_LD_inner.py 79
python encode_sfu_AI_inner.py 9
python encode_sfu_AI_inner.py 23
python encode_sfu_AI_inner.py 37
python encode_sfu_AI_inner.py 51
python encode_sfu_AI_inner.py 65
python encode_sfu_AI_inner.py 79
python encode_tvd_tracking_RA_e2e.py 9
python encode_tvd_tracking_RA_e2e.py 23
python encode_tvd_tracking_RA_e2e.py 37
python encode_tvd_tracking_RA_e2e.py 51
python encode_tvd_tracking_RA_e2e.py 65
python encode_tvd_tracking_RA_e2e.py 79
python encode_tvd_tracking_LD_e2e.py 9
python encode_tvd_tracking_LD_e2e.py 23
python encode_tvd_tracking_LD_e2e.py 37
python encode_tvd_tracking_LD_e2e.py 51
python encode_tvd_tracking_LD_e2e.py 65
python encode_tvd_tracking_LD_e2e.py 79
python encode_tvd_tracking_AI_e2e.py 9
python encode_tvd_tracking_AI_e2e.py 23
python encode_tvd_tracking_AI_e2e.py 37
python encode_tvd_tracking_AI_e2e.py 51
python encode_tvd_tracking_AI_e2e.py 65
python encode_tvd_tracking_AI_e2e.py 79
python encode_tvd_tracking_RA_inner.py 9
python encode_tvd_tracking_RA_inner.py 23
python encode_tvd_tracking_RA_inner.py 37
python encode_tvd_tracking_RA_inner.py 51
python encode_tvd_tracking_RA_inner.py 65
python encode_tvd_tracking_RA_inner.py 79
python encode_tvd_tracking_LD_inner.py 9
python encode_tvd_tracking_LD_inner.py 23
python encode_tvd_tracking_LD_inner.py 37
python encode_tvd_tracking_LD_inner.py 51
python encode_tvd_tracking_LD_inner.py 65
python encode_tvd_tracking_LD_inner.py 79
python encode_tvd_tracking_AI_inner.py 9
python encode_tvd_tracking_AI_inner.py 23
python encode_tvd_tracking_AI_inner.py 37
python encode_tvd_tracking_AI_inner.py 51
python encode_tvd_tracking_AI_inner.py 65
python encode_tvd_tracking_AI_inner.py 79
